### PR TITLE
Update README.md, package.json and add bower.json

### PR DESCRIPTION
**Pull request by ghost**
Create a new version tag, then publish it to the npm registry please! (even if you won't merge this pull request).

``` bash
$ npm publish
```

Install bower and add your package to the bower registry:

``` bash
$ sudo npm install -g bower
$ bower register jquery.ns-autogrow git://github.com/ro31337/jquery.ns-autogrow.git
```

### CODE REVIEW

**Comment by ghost** [comment]
#11

**Comment by ro31337** [comment]
Thanks, should be done now. Please verify, I'll close issue if it's OK.

@dcdeiv

**Comment by ghost** [comment]
Npm is ok now!
Please let me know if you publish the package to the bower registry!
I you won't publish your package to the bower registry you should delete the `bower.json` file. But I recommend you to publish it!

**Comment by ro31337** [comment]
Should be published to bower registry already, can you check if it works? Thanks!

**Comment by ghost** [comment]
Yes! The package is published!
In the next release, consider to change the `main` data from `"main": "dist/jquery.ns-autogrow.min.js"` to `"main": "dist/jquery.ns-autogrow.js",` because it throws an error: `bower invalid-meta  The "main" field cannot contain minified files`.

This fix is however not so important since the package is still delivered!

**Comment by ghost** [comment]
Also thank you!

**Comment by ro31337** [comment]
Thanks, I fixed this complaint here: https://github.com/ro31337/jquery.ns-autogrow/commit/cefc592e362efeabe9e7dac451bd92f0e48959c1

I appreciate if you can check if it works. Thanks!

**Comment by ghost** [comment]
Everything is working!

**Pull request merged**
